[versions]
# ANDROID
agp = "8.13.0"
compileSdk = "36"
minSdk = "26"
targetSdk = "36"

# ANDROIDX
androidx-appcompat = "1.7.1"
androidx-core = "1.18.0"
androidx-lifecycle = "2.10.0"
androidx-material = "1.13.0"

# COMPOSE
compose-bom = "2026.04.01"

# COMPOSE MULTIPLATFORM
compose-multiplatform = "1.10.3"

# DATA STORE
data-store = "1.2.0"

# DETEKT
detekt = "1.23.8"

# KCTFORK
kctfork = "0.13.0"

# KOIN
koin = "4.2.1"

# KOTLIN
kotlin = "2.3.21"
kotlinx-coroutines = "1.10.2"
kotlinx-immutableCollections = "0.4.0"
kotlinx-serialization = "1.9.0"

# KSP
ksp = "2.3.9"

# OKIO
okio = "3.10.2"

# PUBLISH
publish = "0.36.0"

# TEST
junit = "4.13.2"
junit-ext = "1.3.0"
mockk = "1.14.9"
test-core = "1.6.1"
test-runner = "1.7.0"
turbine = "1.2.1"

[libraries]
# ANDROIDX
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }

# COMPOSE
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
material3 = { group = "androidx.compose.material3", name = "material3" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

# COMPOSE MULTIPLATFORM
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }

# DATA STORE
data-store = { module = "androidx.datastore:datastore", version.ref = "data-store" }
data-store-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "data-store" }
datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "data-store" }

# DETEKT
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

# KCTFORK
kctfork-core = { module = "dev.zacsweers.kctfork:core", version.ref = "kctfork" }
kctfork-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kctfork" }

# KOIN
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-android-test = { module = "io.insert-koin:koin-android-test", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

# KOTLIN
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutableCollections" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# KSP
symbol-processing = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }

# OKIO
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

# TEST
androidx-test-core = { module = "androidx.test:core", version.ref = "test-core" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
publish = { id = "com.vanniktech.maven.publish", version.ref = "publish" }
